// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v2/chat.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_Type int32

const (
	Request_SEND_MESSAGE Request_Type = 0
	Request_UPDATE_PEER  Request_Type = 1
)

var Request_Type_name = map[int32]string{
	0: "SEND_MESSAGE",
	1: "UPDATE_PEER",
}

var Request_Type_value = map[string]int32{
	"SEND_MESSAGE": 0,
	"UPDATE_PEER":  1,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}

func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d771c1ecc38b4be, []int{0, 0}
}

type Request struct {
	Type                 Request_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.Request_Type" json:"type,omitempty"`
	SendMessage          *SendMessage `protobuf:"bytes,2,opt,name=sendMessage,proto3" json:"sendMessage,omitempty"`
	UpdatePeer           *UpdatePeer  `protobuf:"bytes,3,opt,name=updatePeer,proto3" json:"updatePeer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d771c1ecc38b4be, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_SEND_MESSAGE
}

func (m *Request) GetSendMessage() *SendMessage {
	if m != nil {
		return m.SendMessage
	}
	return nil
}

func (m *Request) GetUpdatePeer() *UpdatePeer {
	if m != nil {
		return m.UpdatePeer
	}
	return nil
}

type SendMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Id                   []byte   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}
func (*SendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d771c1ecc38b4be, []int{1}
}

func (m *SendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage.Unmarshal(m, b)
}
func (m *SendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage.Marshal(b, m, deterministic)
}
func (m *SendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage.Merge(m, src)
}
func (m *SendMessage) XXX_Size() int {
	return xxx_messageInfo_SendMessage.Size(m)
}
func (m *SendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage proto.InternalMessageInfo

func (m *SendMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendMessage) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *SendMessage) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type UpdatePeer struct {
	UserHandle           []byte   `protobuf:"bytes,1,opt,name=userHandle,proto3" json:"userHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePeer) Reset()         { *m = UpdatePeer{} }
func (m *UpdatePeer) String() string { return proto.CompactTextString(m) }
func (*UpdatePeer) ProtoMessage()    {}
func (*UpdatePeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d771c1ecc38b4be, []int{2}
}

func (m *UpdatePeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePeer.Unmarshal(m, b)
}
func (m *UpdatePeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePeer.Marshal(b, m, deterministic)
}
func (m *UpdatePeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePeer.Merge(m, src)
}
func (m *UpdatePeer) XXX_Size() int {
	return xxx_messageInfo_UpdatePeer.Size(m)
}
func (m *UpdatePeer) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePeer.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePeer proto.InternalMessageInfo

func (m *UpdatePeer) GetUserHandle() []byte {
	if m != nil {
		return m.UserHandle
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*SendMessage)(nil), "proto.SendMessage")
	proto.RegisterType((*UpdatePeer)(nil), "proto.UpdatePeer")
}

func init() { proto.RegisterFile("proto/v2/chat.proto", fileDescriptor_0d771c1ecc38b4be) }

var fileDescriptor_0d771c1ecc38b4be = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x4d, 0x57, 0x1d, 0xdc, 0x96, 0x59, 0xef, 0x5e, 0xfa, 0x24, 0xa3, 0x2f, 0x4e, 0x90,
	0x0e, 0xab, 0x7f, 0x60, 0xb0, 0xa0, 0x20, 0x93, 0x92, 0x6e, 0xcf, 0x23, 0x2e, 0x17, 0x1d, 0xc8,
	0x56, 0x9b, 0x54, 0xd8, 0x1f, 0xf4, 0x77, 0x89, 0xd7, 0x6a, 0xf3, 0x94, 0xdc, 0x9c, 0xef, 0xe6,
	0x9c, 0x03, 0xe3, 0xba, 0x39, 0xb8, 0xc3, 0xec, 0xb3, 0x98, 0x6d, 0xdf, 0xb4, 0xcb, 0x79, 0xc2,
	0x53, 0x3e, 0xb2, 0x2f, 0x01, 0x43, 0x45, 0x1f, 0x2d, 0x59, 0x87, 0x57, 0x10, 0xba, 0x63, 0x4d,
	0xa9, 0x98, 0x88, 0xe9, 0xa8, 0x18, 0xff, 0x82, 0x79, 0xa7, 0xe6, 0xab, 0x63, 0x4d, 0x8a, 0x01,
	0xbc, 0x87, 0xc8, 0xd2, 0xde, 0x2c, 0xc9, 0x5a, 0xfd, 0x4a, 0x69, 0x30, 0x11, 0xd3, 0xa8, 0xc0,
	0x8e, 0xaf, 0x7a, 0x45, 0xf9, 0x18, 0xde, 0x02, 0xb4, 0xb5, 0xd1, 0x8e, 0x4a, 0xa2, 0x26, 0x1d,
	0xf0, 0xd2, 0x45, 0xb7, 0xb4, 0xfe, 0x17, 0x94, 0x07, 0x65, 0xd7, 0x10, 0xfe, 0xd8, 0x62, 0x02,
	0x71, 0x25, 0x9f, 0x17, 0x9b, 0xa5, 0xac, 0xaa, 0xf9, 0x83, 0x4c, 0x4e, 0xf0, 0x1c, 0xa2, 0x75,
	0xb9, 0x98, 0xaf, 0xe4, 0xa6, 0x94, 0x52, 0x25, 0x22, 0x7b, 0x82, 0xc8, 0x73, 0x46, 0x84, 0xd0,
	0x68, 0xa7, 0xb9, 0x4b, 0xac, 0xf8, 0x8e, 0x29, 0x0c, 0xb7, 0x0d, 0x69, 0x47, 0x86, 0x23, 0x0f,
	0xd4, 0xdf, 0x88, 0x23, 0x08, 0x76, 0x86, 0x23, 0xc5, 0x2a, 0xd8, 0x99, 0xec, 0x06, 0xa0, 0x4f,
	0x84, 0x97, 0x00, 0xad, 0xa5, 0xe6, 0x51, 0xef, 0xcd, 0x3b, 0x75, 0x3f, 0x7a, 0x2f, 0x2f, 0x67,
	0xdc, 0xe1, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x15, 0xc5, 0x42, 0x2a, 0x68, 0x01, 0x00, 0x00,
}
